"""Initial schema according to Rev 4

Revision ID: 847924ad5257
Revises:
Create Date: 2026-09-02 20:38:24.314503

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "847924ad5257"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "customers",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("razorpay_customer_id", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("phone", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("razorpay_customer_id"),
    )
    op.create_table(
        "webhook_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("razorpay_event_id", sa.String(), nullable=False),
        sa.Column("event_type", sa.String(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("signature_verified", sa.Boolean(), nullable=False),
        sa.Column("processed", sa.Boolean(), nullable=False),
        sa.Column("processing_error", sa.String(), nullable=True),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("razorpay_event_id"),
    )
    op.create_index(
        "ix_webhook_events_processed", "webhook_events", ["processed"], unique=False
    )
    op.create_table(
        "payments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("razorpay_payment_id", sa.String(), nullable=False),
        sa.Column("customer_id", sa.UUID(), nullable=True),
        sa.Column("amount", sa.BigInteger(), nullable=False),
        sa.Column("currency", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("error_code", sa.String(), nullable=True),
        sa.Column("error_description", sa.String(), nullable=True),
        sa.Column("error_source", sa.String(), nullable=True),
        sa.Column("error_step", sa.String(), nullable=True),
        sa.Column("error_reason", sa.String(), nullable=True),
        sa.Column("method", sa.String(), nullable=True),
        sa.Column("bank", sa.String(), nullable=True),
        sa.Column("card_network", sa.String(), nullable=True),
        sa.Column("vpa", sa.String(), nullable=True),
        sa.Column("international", sa.Boolean(), nullable=False),
        sa.Column("order_id", sa.String(), nullable=True),
        sa.Column(
            "payload_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("failed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("razorpay_payment_id"),
    )
    op.create_index(
        "ix_payments_status_failed_at",
        "payments",
        ["status", "failed_at"],
        unique=False,
    )
    op.create_table(
        "recovery_cases",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("original_payment_id", sa.String(), nullable=False),
        sa.Column("payment_fk", sa.UUID(), nullable=False),
        sa.Column("customer_id", sa.UUID(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("mode", sa.String(), nullable=False),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("amount_at_risk", sa.BigInteger(), nullable=False),
        sa.Column("amount_recovered", sa.BigInteger(), nullable=False),
        sa.Column("recovered_payment_id", sa.String(), nullable=True),
        sa.Column(
            "recovery_window_expires_at", sa.DateTime(timezone=True), nullable=False
        ),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("stop_reason", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["payment_fk"],
            ["payments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("original_payment_id"),
        sa.UniqueConstraint("payment_fk"),
    )
    op.create_index(
        "ix_recovery_cases_mode_status",
        "recovery_cases",
        ["mode", "status"],
        unique=False,
    )
    op.create_index(
        "ix_recovery_cases_status_due_at",
        "recovery_cases",
        ["status", "due_at"],
        unique=False,
    )
    op.create_index(
        "ix_recovery_cases_status_window_expires",
        "recovery_cases",
        ["status", "recovery_window_expires_at"],
        unique=False,
    )
    op.create_table(
        "recovery_decisions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("case_id", sa.UUID(), nullable=False),
        sa.Column("attempt_number", sa.Integer(), nullable=False),
        sa.Column("recommended_action", sa.String(), nullable=False),
        sa.Column("llm_confidence", sa.Float(), nullable=False),
        sa.Column("delay_hours", sa.Integer(), nullable=True),
        sa.Column("reason", sa.String(), nullable=False),
        sa.Column(
            "risk_factors", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("heuristic_recovery_likelihood", sa.Float(), nullable=True),
        sa.Column("policy_verdict", sa.String(), nullable=False),
        sa.Column("effective_action", sa.String(), nullable=False),
        sa.Column(
            "policy_modification_detail",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("policy_reason", sa.String(), nullable=False),
        sa.Column(
            "raw_llm_response", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("llm_provider", sa.String(), nullable=False),
        sa.Column("llm_model", sa.String(), nullable=False),
        sa.Column("llm_latency_ms", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["recovery_cases.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "recovery_actions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("case_id", sa.UUID(), nullable=False),
        sa.Column("decision_id", sa.UUID(), nullable=False),
        sa.Column("attempt_number", sa.Integer(), nullable=False),
        sa.Column("action_type", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("idempotency_key", sa.String(), nullable=False),
        sa.Column("razorpay_link_id", sa.String(), nullable=True),
        sa.Column("razorpay_link_short_url", sa.String(), nullable=True),
        sa.Column("razorpay_link_reference_id", sa.String(), nullable=True),
        sa.Column("razorpay_link_expire_by", sa.DateTime(timezone=True), nullable=True),
        sa.Column("executed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("outcome", sa.String(), nullable=True),
        sa.Column("outcome_observed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failure_reason", sa.String(), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["recovery_cases.id"],
        ),
        sa.ForeignKeyConstraint(
            ["decision_id"],
            ["recovery_decisions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key"),
    )
    op.create_index(
        "ix_recovery_actions_case_id_attempt",
        "recovery_actions",
        ["case_id", "attempt_number"],
        unique=False,
    )
    op.create_index(
        "ix_recovery_actions_reference_id",
        "recovery_actions",
        ["razorpay_link_reference_id"],
        unique=False,
    )
    op.create_table(
        "audit_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("case_id", sa.UUID(), nullable=True),
        sa.Column("action_id", sa.UUID(), nullable=True),
        sa.Column("event_type", sa.String(), nullable=False),
        sa.Column("actor", sa.String(), nullable=False),
        sa.Column("mode", sa.String(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["action_id"],
            ["recovery_actions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["recovery_cases.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_audit_events_case_id_created_at",
        "audit_events",
        ["case_id", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_audit_events_case_id_created_at", table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_index("ix_recovery_actions_reference_id", table_name="recovery_actions")
    op.drop_index("ix_recovery_actions_case_id_attempt", table_name="recovery_actions")
    op.drop_table("recovery_actions")
    op.drop_table("recovery_decisions")
    op.drop_index(
        "ix_recovery_cases_status_window_expires", table_name="recovery_cases"
    )
    op.drop_index("ix_recovery_cases_status_due_at", table_name="recovery_cases")
    op.drop_index("ix_recovery_cases_mode_status", table_name="recovery_cases")
    op.drop_table("recovery_cases")
    op.drop_index("ix_payments_status_failed_at", table_name="payments")
    op.drop_table("payments")
    op.drop_index("ix_webhook_events_processed", table_name="webhook_events")
    op.drop_table("webhook_events")
    op.drop_table("customers")
    # ### end Alembic commands ###
